apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- deployment.yaml
- service.yaml
replicas:
- name: vote
  count: 1
images:
<<<<<<< HEAD
- name: schoolofdevops/vote
  newTag: main-b654c5d7-1758915028 #{"$imagepolicy":"flux-system:vote:tag"}
=======
  - name: schoolofdevops/vote
    newName: alexlek/vote
    newTag: v6 #{"$imagepolicy":"flux-system:vote:tag"}

>>>>>>> 59a975e (change image tagname)
namespace: instavote
commonLabels:
  project: instavote
  env: staging
commonAnnotations:
  supported-by: "sre@sre.com"
configMapGenerator:
- name: vote-options
  envs:
  - options.env
